# Generated by Django 5.0 on 2024-05-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0014_ad_distributor_notification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='images',
            field=models.TextField(null=True),
        ),
    ]
