# Generated by Django 5.0 on 2024-08-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_private_investigator_notification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.TextField()),
                ('user2', models.TextField()),
                ('chat', models.JSONField(default=list)),
            ],
        ),
    ]
