# Generated by Django 5.0 on 2024-07-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_pi_performance_calculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(null=True)),
                ('currency', models.TextField(null=True)),
                ('marital_status', models.TextField(null=True)),
                ('physical_status', models.TextField(null=True)),
                ('cast', models.TextField(null=True)),
                ('type_of_relationship', models.TextField(null=True)),
                ('education', models.TextField(null=True)),
                ('job_position', models.TextField(null=True)),
                ('salary_range', models.TextField(null=True)),
                ('intrest', models.TextField(null=True)),
                ('no_intrest', models.TextField(null=True)),
                ('complexion', models.TextField(null=True)),
                ('food_taste', models.TextField(null=True)),
                ('organs', models.TextField(null=True)),
                ('familystatus', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('values', models.TextField(null=True)),
            ],
        ),
    ]
