# Generated by Django 5.0 on 2024-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdown',
            name='cities',
            field=models.TextField(null=True),
        ),
    ]
