# Generated by Django 5.0 on 2024-08-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_dropdown_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummy_matching_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(null=True)),
                ('username', models.TextField(null=True)),
                ('userid', models.TextField(null=True)),
                ('tagline', models.TextField(null=True)),
            ],
        ),
    ]
